---
title: "Getting started"
---

## Installation 

### R installation

R is a free language and environment for statistical computing and graphics. It
is available for download [here](https://ftp.fau.de/cran/).

### RStudio installation

RStudio is a free integrated development environment (IDE) for R, which makes
using R a lot easier. It can be downloaded 
[here](https://www.rstudio.com/products/rstudio/download/#download).
In these tutorials, it is assumed that RStudio is used.

## R code

### Coding in R

R code is organized in *scripts*. Scripts are files ending in `.R` and can 
contain R code and comments (preceded by `#`), e.g. file `myfile.R` containing

```{r}
1 + 1 # an easy summation
```

In RStudio, a new script is created by clicking on `File/New File/R Script` or  
the `+` sign at the top left of the IDE.

### Running R code in RStudio

R code can be run at the console (by typing `Enter`) or from an R script:

* per line or per selection by clicking on `Run` 
* entire R files can be `source`'d, running `source("myfile.R")` either on the 
  command line or from another R script.
